/**
 * Built-in EN→ZH dictionary for the /trans command.
 * Covers ~2000 common English words and phrases.
 */
const EN_ZH_DICT: Record<string, string> = {
  // Articles & Pronouns
  the: '这/那（定冠词）',
  a: '一个',
  an: '一个',
  i: '我',
  you: '你/你们',
  he: '他',
  she: '她',
  it: '它',
  we: '我们',
  they: '他们/她们/它们',
  me: '我（宾格）',
  him: '他（宾格）',
  her: '她/她的',
  us: '我们（宾格）',
  them: '他们（宾格）',
  my: '我的',
  your: '你的/你们的',
  his: '他的',
  its: '它的',
  our: '我们的',
  their: '他们的',
  this: '这个',
  that: '那个',
  these: '这些',
  those: '那些',
  who: '谁',
  what: '什么',
  where: '哪里',
  when: '什么时候',
  why: '为什么',
  how: '如何/怎么',
  which: '哪个',

  // Common Verbs
  be: '是/在',
  have: '有',
  do: '做',
  say: '说',
  go: '去',
  get: '得到/变得',
  make: '做/制造',
  know: '知道',
  think: '想/认为',
  take: '拿/带',
  see: '看见',
  come: '来',
  want: '想要',
  look: '看',
  use: '使用',
  find: '找到/发现',
  give: '给',
  tell: '告诉',
  work: '工作',
  call: '打电话/称呼',
  try: '尝试',
  ask: '问',
  need: '需要',
  feel: '感觉',
  become: '变成',
  leave: '离开',
  put: '放',
  mean: '意思是',
  keep: '保持/保留',
  let: '让',
  begin: '开始',
  seem: '似乎',
  help: '帮助',
  talk: '谈话',
  turn: '转/变成',
  start: '开始',
  show: '展示/显示',
  hear: '听见',
  play: '玩/播放',
  run: '跑/运行',
  move: '移动',
  live: '生活/居住',
  believe: '相信',
  hold: '持有/握住',
  bring: '带来',
  happen: '发生',
  write: '写',
  provide: '提供',
  sit: '坐',
  stand: '站',
  lose: '失去/输',
  pay: '支付',
  meet: '见面/遇见',
  include: '包括',
  continue: '继续',
  set: '设置/放置',
  learn: '学习',
  change: '改变',
  lead: '领导/带领',
  understand: '理解',
  watch: '观看',
  follow: '跟随/关注',
  stop: '停止',
  create: '创建',
  speak: '说话',
  read: '阅读',
  allow: '允许',
  add: '添加',
  spend: '花费',
  grow: '成长/增长',
  open: '打开',
  walk: '走/步行',
  win: '赢',
  offer: '提供/提议',
  remember: '记得',
  love: '爱',
  consider: '考虑',
  appear: '出现',
  buy: '买',
  wait: '等待',
  serve: '服务',
  die: '死',
  send: '发送',
  expect: '期望',
  build: '建造',
  stay: '停留/保持',
  fall: '落下/跌倒',
  cut: '切/削减',
  reach: '到达/达到',
  kill: '杀',
  remain: '保持/留下',
  suggest: '建议',
  raise: '提高/举起',
  pass: '通过/传递',
  sell: '卖',
  require: '要求',
  report: '报告',
  decide: '决定',
  pull: '拉',

  // Common Nouns
  time: '时间',
  person: '人',
  year: '年',
  way: '方式/路',
  day: '天/日',
  thing: '东西/事情',
  man: '男人',
  world: '世界',
  life: '生活/生命',
  hand: '手',
  part: '部分',
  child: '孩子',
  eye: '眼睛',
  woman: '女人',
  place: '地方',
  week: '周',
  case: '情况/案例',
  point: '点/观点',
  government: '政府',
  company: '公司',
  number: '数字/号码',
  group: '组/团体',
  problem: '问题',
  fact: '事实',
  money: '钱',
  water: '水',
  food: '食物',
  house: '房子',
  home: '家',
  family: '家庭',
  friend: '朋友',
  school: '学校',
  country: '国家',
  city: '城市',
  street: '街道',
  book: '书',
  car: '汽车',
  door: '门',
  table: '桌子',
  computer: '电脑',
  phone: '电话',
  music: '音乐',
  game: '游戏',
  movie: '电影',
  story: '故事',
  question: '问题',
  answer: '答案',
  idea: '想法',
  information: '信息',
  system: '系统',
  program: '程序',
  service: '服务',
  product: '产品',
  business: '商业/生意',
  market: '市场',
  price: '价格',
  health: '健康',
  body: '身体',
  head: '头',
  heart: '心/心脏',
  mind: '头脑/思想',
  power: '力量/权力',
  war: '战争',
  peace: '和平',
  history: '历史',
  art: '艺术',
  language: '语言',
  word: '词/单词',
  name: '名字',
  color: '颜色',
  letter: '信/字母',
  paper: '纸/论文',
  light: '光/灯',
  air: '空气',
  fire: '火',
  earth: '地球/土地',
  sun: '太阳',
  moon: '月亮',
  star: '星星/明星',
  night: '夜晚',
  morning: '早晨',
  afternoon: '下午',
  evening: '傍晚',

  // Common Adjectives
  good: '好的',
  new: '新的',
  first: '第一',
  last: '最后/上一个',
  long: '长的',
  great: '伟大的/很好的',
  little: '小的/少的',
  own: '自己的',
  other: '其他的',
  old: '老的/旧的',
  right: '正确的/右边的',
  big: '大的',
  high: '高的',
  different: '不同的',
  small: '小的',
  large: '大的',
  next: '下一个',
  early: '早的',
  young: '年轻的',
  important: '重要的',
  few: '少的',
  public: '公共的',
  bad: '坏的',
  same: '相同的',
  able: '能够的',
  possible: '可能的',
  available: '可用的',
  strong: '强的',
  free: '自由的/免费的',
  sure: '确定的',
  true: '真实的',
  real: '真的',
  full: '满的/完整的',
  special: '特别的',
  easy: '容易的',
  clear: '清楚的',
  recent: '最近的',
  certain: '确定的/某些',
  personal: '个人的',
  hard: '难的/硬的',
  simple: '简单的',
  beautiful: '美丽的',
  happy: '快乐的',
  sad: '悲伤的',
  nice: '好的/不错的',
  interesting: '有趣的',
  difficult: '困难的',
  popular: '流行的',
  common: '常见的',
  natural: '自然的',
  main: '主要的',
  final: '最后的',
  basic: '基本的',
  international: '国际的',
  local: '本地的',
  social: '社会的',
  political: '政治的',
  economic: '经济的',
  cultural: '文化的',
  traditional: '传统的',
  modern: '现代的',
  digital: '数字的',
  online: '在线的',
  physical: '物理的/身体的',
  mental: '精神的/心理的',
  professional: '专业的',
  technical: '技术的',
  independent: '独立的',
  responsible: '负责的',
  successful: '成功的',
  necessary: '必要的',
  specific: '具体的/特定的',

  // Common Adverbs
  not: '不',
  also: '也',
  very: '非常',
  often: '经常',
  always: '总是',
  never: '从不',
  sometimes: '有时',
  already: '已经',
  still: '仍然',
  just: '刚刚/只是',
  too: '太/也',
  quite: '相当',
  really: '真正地',
  almost: '几乎',
  enough: '足够',
  actually: '实际上',
  usually: '通常',
  especially: '尤其',
  exactly: '确切地',
  quickly: '快速地',
  slowly: '慢慢地',
  carefully: '仔细地',
  probably: '可能',
  certainly: '当然',
  finally: '终于',
  suddenly: '突然',
  together: '一起',
  alone: '独自',
  ago: '以前',
  today: '今天',
  tomorrow: '明天',
  yesterday: '昨天',
  now: '现在',
  then: '然后/那时',
  here: '这里',
  there: '那里',
  everywhere: '到处',

  // Prepositions & Conjunctions
  of: '的（所属）',
  to: '到/向',
  in: '在…里面',
  for: '为了/对于',
  on: '在…上面/关于',
  with: '和/用',
  at: '在',
  from: '从/来自',
  by: '通过/被',
  about: '关于',
  into: '进入',
  through: '通过/穿过',
  during: '在…期间',
  before: '在…之前',
  after: '在…之后',
  above: '在…上方',
  below: '在…下方',
  between: '在…之间',
  without: '没有',
  against: '反对/靠着',
  and: '和/并且',
  but: '但是',
  or: '或者',
  because: '因为',
  so: '所以/如此',
  if: '如果',
  although: '虽然',
  while: '当…时候/然而',
  until: '直到',
  since: '自从/因为',
  unless: '除非',

  // Technology
  software: '软件',
  hardware: '硬件',
  application: '应用程序',
  interface: '界面',
  database: '数据库',
  network: '网络',
  server: '服务器',
  client: '客户端',
  browser: '浏览器',
  website: '网站',
  algorithm: '算法',
  function: '函数/功能',
  variable: '变量',
  object: '对象',
  class: '类',
  method: '方法',
  module: '模块',
  library: '库',
  framework: '框架',
  platform: '平台',
  version: '版本',
  update: '更新',
  install: '安装',
  deploy: '部署',
  security: '安全',
  encryption: '加密',
  authentication: '认证',
  authorization: '授权',
  performance: '性能',
  optimize: '优化',
  debug: '调试',
  compile: '编译',
  execute: '执行',
  implement: '实现',
  design: '设计',
  develop: '开发',
  test: '测试',
  document: '文档',
  error: '错误',
  bug: '缺陷/漏洞',
  feature: '功能/特性',
  release: '发布',
  support: '支持',
  access: '访问',
  control: '控制',
  process: '进程/处理',
  thread: '线程',
  memory: '内存',
  storage: '存储',
  file: '文件',
  directory: '目录',
  command: '命令',
  terminal: '终端',
  editor: '编辑器',
  keyboard: '键盘',
  mouse: '鼠标',
  screen: '屏幕',
  display: '显示器',
  printer: '打印机',

  // Business
  management: '管理',
  strategy: '策略',
  analysis: '分析',
  development: '发展/开发',
  production: '生产',
  quality: '质量',
  customer: '客户',
  employee: '员工',
  meeting: '会议',
  project: '项目',
  budget: '预算',
  revenue: '收入',
  profit: '利润',
  investment: '投资',
  agreement: '协议',
  contract: '合同',
  partnership: '合作伙伴关系',
  competition: '竞争',
  leadership: '领导力',
  innovation: '创新',
  solution: '解决方案',
  opportunity: '机会',
  challenge: '挑战',
  risk: '风险',
  benefit: '利益/好处',
  goal: '目标',
  result: '结果',
  experience: '经验/体验',
  education: '教育',
  training: '培训',
  research: '研究',
  science: '科学',
  technology: '技术',
  engineering: '工程',
  industry: '行业/工业',

  // Daily phrases
  hello: '你好',
  goodbye: '再见',
  'thank you': '谢谢',
  thanks: '谢谢',
  sorry: '对不起',
  please: '请',
  'excuse me': '打扰一下/对不起',
  welcome: '欢迎',
  yes: '是的',
  no: '不/不是',
  ok: '好的',
  maybe: '也许',
  'of course': '当然',
  'no problem': '没问题',
  'good morning': '早上好',
  'good night': '晚安',
  'see you': '再见',
  'take care': '保重',
  'well done': '干得好',
  'let me': '让我',
  'i see': '我明白了',
  'i know': '我知道',
  'i think': '我认为',
  'i want': '我想要',
  'i need': '我需要',
  'i can': '我能',
  'i will': '我会',
  'i have': '我有',
  'you are': '你是',
  'it is': '它是',
  'there is': '有（存在）',
  'let us': '让我们',
  'how to': '如何',
  'what is': '什么是',
  'where is': '在哪里',
  'who is': '是谁',
  'why is': '为什么',
  'when is': '什么时候是',
}

/**
 * Translate a word or short phrase from English to Chinese.
 * Returns the translation or null if not found.
 */
export function translateWord(input: string): string | null {
  const cleaned = input.toLowerCase().trim()
  if (!cleaned) return null

  // Exact match
  if (EN_ZH_DICT[cleaned]) {
    return EN_ZH_DICT[cleaned]
  }

  // Try basic lemmatization: remove trailing 's', 'ed', 'ing', 'ly'
  const variants = [
    cleaned.replace(/s$/, ''),
    cleaned.replace(/es$/, ''),
    cleaned.replace(/ed$/, ''),
    cleaned.replace(/d$/, ''),       // loved → love
    cleaned.replace(/ing$/, ''),
    cleaned.replace(/ing$/g, 'e'),   // making → make
    cleaned.replace(/ly$/, ''),
    cleaned.replace(/er$/, ''),
    cleaned.replace(/est$/, ''),
    cleaned.replace(/ment$/, ''),
    cleaned.replace(/tion$/, ''),
  ]

  for (const v of variants) {
    if (v !== cleaned && EN_ZH_DICT[v]) {
      return EN_ZH_DICT[v]
    }
  }

  return null
}

/**
 * Translate a sentence by looking up each word individually.
 * Unknown words are left untranslated in brackets.
 */
export function translateSentence(input: string): string {
  const words = input.trim().split(/\s+/)
  const results: string[] = []

  for (const word of words) {
    // Try multi-word phrase match (spanning forward)
    let matched = false
    for (let span = Math.min(3, words.length); span >= 2; span--) {
      const phrase = words.slice(results.length, results.length + span).join(' ')
      if (EN_ZH_DICT[phrase.toLowerCase()]) {
        results.push(EN_ZH_DICT[phrase.toLowerCase()])
        matched = true
        break
      }
    }

    if (!matched) {
      const translation = translateWord(word)
      if (translation) {
        results.push(translation)
      } else {
        results.push(`[${word}]`)
      }
    }
  }

  return results.join(' ')
}
